
routes:

  - pattern: task/
    route-name: task-listing

  - pattern: task/create
    route-name: task-create

  - pattern: task/edit/:id
    route-name: task-edit

  - pattern: task/comment/:id
    route-name: task-comment

  - pattern: task/:id
    route-name: task-display
