
routes:

  - route-name: main-listing
    pattern: disq/
  - route-name: main-listing
    pattern: disq/page/:page-nr

  - route-name: disq-creation
    pattern: disq/create
  - route-name: disq-creation
    pattern: disq/:id/edit

  - route-name: disq-display
    pattern: disq/:id
  - route-name: disq-display
    pattern: disq/:id/page/:page-nr

  - route-name: disq-posting
    pattern: disq/:disq-id/post
  - route-name: disq-posting
    pattern: disq/:disq-id/:post-id/edit

  - route-name: forum-comment
    pattern: forum/:id/comment
