
parameters:
    # Paths
    # project.root: /path/to/project/
    project.cache: cache/
    project.src:   src/

    # MongoDB
    mongodb.host: localhost
    mongodb.db:   modhub
    mongodb.port: 27017
    mongodb.collection.logger: monolog
    mongodb.collection.cache: cache

    # Doctrine
    doctrine.proxy.path: null

user-security:
  providerKey: ModHub

services:

  # ----------------------------------------------------------------------------
  # Generic
  # ----------------------------------------------------------------------------

  request_stack:
    class: Symfony\Component\HttpFoundation\RequestStack
    synthetic: true

  http_kernel:
    class: AnhNhan\ModHub\Web\HttpKernel
    synthetic: true

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    synthetic: true

  # ----------------------------------------------------------------------------
  # MongoDB
  # ----------------------------------------------------------------------------

  mongoclient:
    class: MongoClient
    arguments: ["mongodb://%mongodb.host%:%mongodb.port%"]
  mongodb:
    class: MongoDB
    factory_service: mongoclient
    factory_method:  selectDB
    arguments: ["%mongodb.db%"]

  # ----------------------------------------------------------------------------
  # Resource handling
  # ----------------------------------------------------------------------------

  resource_manager:
    class: AnhNhan\ModHub\Modules\StaticResources\ResMgr
    synthetic: true

  # ----------------------------------------------------------------------------
  # Caches
  # ----------------------------------------------------------------------------

  mongodb.collection.cache:
    class: MongoCollection
    public: false
    factory_service: mongodb
    factory_method: selectCollection
    arguments: ["%mongodb.collection.cache%"]
  cache.mongodb:
    class: Doctrine\Common\Cache\MongoDBCache
    arguments: ["@mongodb.collection.cache"]
    tags:
      - { name: cache }

  cache.filesystem:
    class: Doctrine\Common\Cache\FilesystemCache
    arguments: ["%project.root%%project.cache%"]
    tags:
      - { name: cache }

  cache.default:
    alias: cache.filesystem
    tags:
      - { name: cache }

  cache.resmgr:
    alias: cache.default
    tags:
      - { name: cache }

  cache.doctrine:
    alias: cache.mongodb
    tags:
      - { name: cache }

  stopwatch:
    class: Symfony\Component\Stopwatch\Stopwatch

  # ----------------------------------------------------------------------------
  # Logging
  # ----------------------------------------------------------------------------

  logger_mongohandler:
    class: Monolog\Handler\MongoDBHandler
    arguments: ["@mongoclient", "%mongodb.db%", "%mongodb.collection.logger%"]
    public: false
  logger_psrprocessor:
    class: Monolog\Processor\PsrLogMessageProcessor
    public: false
  logger_memoryprocessor:
    class: Monolog\Processor\MemoryUsageProcessor
    public: false
  logger_introspectionprocessor:
    class: Monolog\Processor\IntrospectionProcessor
    public: false
  logger:
    class: Monolog\Logger
    arguments:
      - "default"
      - ["@logger_mongohandler"]
      - ["@logger_psrprocessor", "@logger_memoryprocessor", "@logger_introspectionprocessor"]
