---
vagrantfile-local:
    vm:
        box: debian-wheezy72-x64-vbox43
        box_url: 'http://box.puphpet.com/debian-wheezy72-x64-vbox43.box'
        hostname: null
        network:
            private_network: 192.168.56.101
            forwarded_port:
                w07XzdzV6aTB:
                    host: '6728'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet/manifests
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            J85ZU5l4ByYc:
                id: vagrant-root
                source: ./
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: ':detect'
server:
    packages: {  }
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
apache:
    modules:
        - php
        - rewrite
    vhosts:
        lYDq5T49pGtG:
            servername: awesome.dev
            serveraliases:
                - www.awesome.dev
            docroot: /var/www/awesome
            port: '80'
            setenv:
                - 'APP_ENV dev'
            override:
                - All
    user: www-data
    group: www-data
    default_vhost: true
    mpm_module: prefork
    mod_pagespeed: 0
    mod_spdy: 0
php:
    version: '54'
    composer: '1'
    modules:
        php:
            - cli
            - intl
            - mcrypt
            # Built into Ubuntu
            # - mbstring
            - readline
            - xsl
            - cgi
            - common
            - curl
            - fpm
            - gd
        pear: {  }
        pecl:
            - APC
            - memcached
            - varnish
            - mongo
            - PDO
            - PDO_MYSQL
            - PDO_PGSQL
            - PDO_SQLITE
            - redis
            - zip
            - intl
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: UTC
xdebug:
    #install: '1'
    install: '0'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
xhprof:
    install: '0'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    root_password: roots_super_secret_password
    phpmyadmin: '1'
    adminer: 0
    databases:
        QzoljHnxhSaP:
            grant:
                - ALL
            name: modhub_forum
            host: localhost
            user: modhub
            password: modhub
            sql_file: ''
        r198Vb5WTrAN:
            grant:
                - ALL
            name: modhub_tag
            host: localhost
            user: modhub
            password: modhub
            sql_file: ''
        qCrRwGO6n1vR:
            grant:
                - ALL
            name: modhub_user
            host: localhost
            user: modhub
            password: modhub
            sql_file: ''
beanstalkd:
    install: '1'
    listenaddress: 0.0.0.0
    listenport: '13000'
    maxjobsize: '65535'
    maxconnections: '1024'
    binlogdir: /var/lib/beanstalkd/binlog
    binlogfsync: null
    binlogsize: '10485760'

