
parameters:
  entity.user.user.class: AnhNhan\Converge\Modules\User\Storage\User

services:

  application.user:
    synthetic: true

  application.user.entitymanager:
    class: Doctrine\ORM\EntityManager
    factory_service: application.user
    factory_method:  getEntityManager
