
/* Table creation */

CREATE TABLE Tag (id VARCHAR(255) NOT NULL, `label` VARCHAR(255) NOT NULL, displayOrder INT NOT NULL, color VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, createdAt DATETIME NOT NULL, modifiedAt DATETIME NOT NULL, UNIQUE INDEX UNIQ_3BC4F163EA750E8 (`label`), INDEX label_sorting (`label`, displayOrder), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE TagTransaction (id VARCHAR(255) NOT NULL, object_id VARCHAR(255) DEFAULT NULL, actor VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, oldValue LONGTEXT DEFAULT NULL, newValue LONGTEXT DEFAULT NULL, metadata LONGTEXT NOT NULL, createdAt DATETIME NOT NULL, modifiedAt DATETIME NOT NULL, INDEX IDX_FF9F80F7232D562B (object_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
ALTER TABLE TagTransaction ADD CONSTRAINT FK_FF9F80F7232D562B FOREIGN KEY (object_id) REFERENCES Tag (id);
