<?php
// -----------------------------------------------------------------------------
/**
 *  This file was generated by the SymbolGenerator(tm)
 *  Would be cool if you wouldn't edit it, as that would sure break things
 *
 *  To re-generate this file, run `php -f scripts/generate_symbol_list.php`
 *
 *  Thank you
 *  @love Anh Nhan <anhnhan@outlook.com>
 *
 *  @generated
 */
// -----------------------------------------------------------------------------

return array(
  "locations" => array(
    "functions" => array(
      "get_root" => "AnhNhan/ModHub/functions.php",
      "get_root_super" => "AnhNhan/ModHub/functions.php",
      "path" => "AnhNhan/ModHub/functions.php",
      "is_cli" => "AnhNhan/ModHub/functions.php",
      "is_windows" => "AnhNhan/ModHub/functions.php",
      "println" => "AnhNhan/ModHub/functions.php",
      "sdx" => "AnhNhan/ModHub/functions.php",
      "pdx" => "AnhNhan/ModHub/functions.php",
    ),
    "classes" => array(
    ),
  ),
  "xmap" => array(
    "derivations" => array(
    ),
    "implementations" => array(
    ),
  ),
);
